FROM ubuntu:20.04
RUN apt-get update 
RUN apt-get upgrade -y
RUN apt-get install -y python3.9
RUN apt install -y python3-pip
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.9 1
WORKDIR /workspace
ADD . /workspace/
RUN pip install -r requirements.txt
ENV HOME=/workspace
RUN src/graph/GUI.py
